spring:
  application:
    name: chatgpt-clone-backend
  ai:
    azure:
      openai:
        api-key: ${AZURE_OPENAI_API_KEY}
        endpoint: ${AZURE_OPENAI_ENDPOINT}
        chat:
          options:
            deployment-name: o4-mini
            temperature: 1
        image:
          options:
            deployment-name: FLUX-1.1-pro
        audio:
          transcription:
            options:
              deployment-name: whisper

  datasource:
    url: jdbc:postgresql://localhost:5432/chatgpt_clone
    username: meet
    password: 1234

  main:
    allow-bean-definition-overriding: true

  sql:
    init:
      mode: always
      schema-locations: classpath:init/schema.sql

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
